# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "test"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
authors = [ "mac" ]
description = "abc"

[features]
default = ["std"]
std = ["concordium-std/std", "concordium-cis2/std"]
wee_alloc = ["concordium-std/wee_alloc"]

[dependencies]
concordium-std = {version = "*", default-features = false}
concordium-cis2 = "*"
chrono = "0.4.26"


[dev-dependencies]
concordium-smart-contract-testing = "1.0"

[lib]
crate-type=["cdylib", "rlib"]
